CREATE TABLE USERS(
	IDUSER SERIAL,
	NAMEUSER VARCHAR(45),
	CONSTRAINT USERS_PK_1 PRIMARY KEY (IDUSER)
);

CREATE TABLE TEAMS(
	IDTEAM SERIAL,
	NAMETEAM VARCHAR(45),
	SHORTNAME VARCHAR(5),
	CONSTRAINT TEAMS_PK PRIMARY KEY(IDTEAM)
);

CREATE TABLE MATCHES(
	IDMATCH SERIAL,
	IDHOMETEAM INTEGER,
	IDAWAYTEAM INTEGER,
	STATUS VARCHAR(15),
	WINNER INTEGER,
	CONSTRAINT MATCHES_PK_1 PRIMARY KEY (IDMATCH),
	CONSTRAINT MATCHES_FK_1 FOREIGN KEY (IDHOMETEAM) REFERENCES TEAMS (IDTEAM),
	CONSTRAINT MATCHES_FK_2 FOREIGN KEY (IDAWAYTEAM) REFERENCES TEAMS (IDTEAM)
);

CREATE TABLE BETS(
	IDBET SERIAL,
	IDUSER INTEGER,
	CONSTRAINT BETS_PK_1 PRIMARY KEY(IDBET),
	CONSTRAINT BETS_FK_1 FOREIGN KEY(IDUSER) REFERENCES USERS(IDUSER)
);

CREATE TABLE SHOTS(
	IDSHOT SERIAL,
	IDBET INTEGER,
	IDMATCH INTEGER,
	WINER INTEGER,
	CONSTRAINT SHOTS_PK_1 PRIMARY KEY(IDSHOT, IDBET),
	CONSTRAINT SHOTS_FK_1 FOREIGN KEY(IDBET) REFERENCES BETS(IDBET),
	CONSTRAINT SHOTS_FK_2 FOREIGN KEY(IDMATCH) REFERENCES MATCHES(IDMATCH)
);

--CRIE ESSA FUNÇÃO NO SEU BANCO
CREATE OR REPLACE FUNCTION GETALLMATCHES() RETURNS TABLE (
	IDMATCH INTEGER,
	IDHOMETEAM INTEGER,
	IDAWAYTEAM INTEGER,
	STATUS VARCHAR(15),
	WINNER INTEGER,
	NAMEHOMETEAM VARCHAR(45),
	NAMEAWAYTEAM VARCHAR (45),
	SHORTNAMEHOMETEAM VARCHAR(45),
	SHORTNAMEAWAYTEAM VARCHAR (45)) AS
$$
BEGIN
	RETURN QUERY
	SELECT M.IDMATCH, M.IDHOMETEAM, M.IDAWAYTEAM, M.STATUS, M.WINNER, HTEAM.NAMETEAM, ATEAM.NAMETEAM, HTEAM.SHORTNAME, ATEAM.SHORTNAME
			FROM MATCHES M, (SELECT * FROM TEAMS T) AS HTEAM, (SELECT * FROM TEAMS) AS ATEAM
			WHERE HTEAM.IDTEAM=M.IDHOMETEAM AND ATEAM.IDTEAM=M.IDAWAYTEAM;
	RETURN;
END;
$$
LANGUAGE PLPGSQL;

SELECT * FROM GETALLMATCHES();
SELECT * FROM GETMATCHEBYTEAMID(2)
SELECT * FROM TEAMS;
							   
--CRIE ESSA FUNÇÃO NO SEU BANCO
CREATE OR REPLACE FUNCTION GETMATCHEBYTEAMID(INT IDTEAM_PARAM) RETURNS TABLE (
	IDMATCH INTEGER,
	IDHOMETEAM INTEGER,
	IDAWAYTEAM INTEGER,
	STATUS VARCHAR(15),
	WINNER INTEGER,
	NAMEHOMETEAM VARCHAR(45),
	NAMEAWAYTEAM VARCHAR (45),
	SHORTNAMEHOMETEAM VARCHAR(45),
	SHORTNAMEAWAYTEAM VARCHAR (45)) AS
$$
BEGIN
	RETURN QUERY
	SELECT M.IDMATCH, M.IDHOMETEAM, M.IDAWAYTEAM, M.STATUS, M.WINNER, HTEAM.NAMETEAM, ATEAM.NAMETEAM, HTEAM.SHORTNAME, ATEAM.SHORTNAME
			FROM MATCHES M, (SELECT * FROM TEAMS T) AS HTEAM, (SELECT * FROM TEAMS) AS ATEAM
			WHERE HTEAM.IDTEAM=M.IDHOMETEAM AND ATEAM.IDTEAM=M.IDAWAYTEAM;
	RETURN;
END;
$$
LANGUAGE PLPGSQL;
