CREATE TABLE USERS(
	IDUSER SERIAL,
	NAMEUSER VARCHAR(45),
	CONSTRAINT USERS_PK_1 PRIMARY KEY (IDUSER)
);

CREATE TABLE MATCHES(
	IDMATCH SERIAL,
	IDHOMETEAM INTEGER,
	IDAWAYTEAM INTEGER,
	DATE_MATCH DATE,
	WINNER INTEGER,
	CONSTRAINT MATCHES_PK_1 PRIMARY KEY (IDMATCH),
	CONSTRAINT MATCHES_FK_1 FOREIGN KEY (IDHOMETEAM) REFERENCES TEAMS (IDTEAM),
	CONSTRAINT MATCHES_FK_2 FOREIGN KEY (IDAWAYTEAM) REFERENCES TEAMS (IDTEAM)
);