CREATE TABLE USERS(
	IDUSER SERIAL,
	NAMEUSER VARCHAR(45),
	CONSTRAINT USERS_PK_1 PRIMARY KEY (IDUSER)
);
CREATE TABLE TEAMS(
	IDTEAM SERIAL,
	NAMETEAM VARCHAR(45),
	SHORTNAME VARCHAR(45),
	CONSTRAINT TEAMS_PK PRIMARY KEY(IDTEAM)
);
CREATE TABLE MATCHES(
	IDMATCH SERIAL,
	IDHOMETEAM INTEGER,
	IDAWAYTEAM INTEGER,
	DATE_MATCH DATE,
	WINNER INTEGER,
	CONSTRAINT MATCHES_PK_1 PRIMARY KEY (IDMATCH),
	CONSTRAINT MATCHES_FK_1 FOREIGN KEY (IDHOMETEAM) REFERENCES TEAMS (IDTEAM),
	CONSTRAINT MATCHES_FK_2 FOREIGN KEY (IDAWAYTEAM) REFERENCES TEAMS (IDTEAM)
);
CREATE TABLE BETS(
	IDBET SERIAL,
	IDUSER INTEGER,
	CONSTRAINT BETS_PK_1 PRIMARY KEY(IDBET),
	CONSTRAINT BETS_FK_1 FOREIGN KEY(IDUSER) REFERENCES USERS(IDUSER)
);

CREATE TABLE SHOTS(
	IDSHOT SERIAL,
	IDBET INTEGER,
	IDMATCH INTEGER,
	WINER INTEGER,
	CONSTRAINT SHOTS_PK_1 PRIMARY KEY(IDSHOT, IDBET),
	CONSTRAINT SHOTS_FK_1 FOREIGN KEY(IDBET) REFERENCES BETS(IDBET),
	CONSTRAINT SHOTS_FK_2 FOREIGN KEY(IDMATCH) REFERENCES MATCHES(IDMATCH)
);
